include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    experimental_member_use: ignore
  plugins:
    - custom_lint

linter:
  rules:
    avoid_print: false
    prefer_final_locals: true
    unawaited_futures: true
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
