name: tfm_app
description: "Predictive Irrigation System integration for Farmers."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.2.0+1

environment:
  sdk: ^3.11.5





dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8           # Icons font. Use with the CupertinoIcons class for iOS style icons.
  flutter_blue_plus: ^2.3.1         # BLE interfacing.
  flutter_blue_plus_linux: ^9.0.0       # Explicitly add linux support.
  http: ^1.6.0                      # HTTP interface. Useful for Open-meteo API transactions.
  tflite_flutter: ^0.12.1           # Tensorflow for mobile and native flutter execution.
  realm: ^20.2.0                    # Database managing.
  flutter_riverpod: ^2.6.1          # State manager.
  signals: ^3.0.0                   # Reactive signals.
  fl_chart: ^0.71.0                 # Powerful charting library.
  geolocator: ^13.0.1               # Location services.
  flutter_map: ^8.0.0               # Interactive maps.
  latlong2: ^0.9.1                  # LatLng types.
  cbor: ^6.5.1                      # CBOR encoding/decoding.
  crypto: ^3.0.3                    # HMAC-SHA256 cryptography.


dev_dependencies:
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0             # Good and Clean coding prsactises.
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.5






# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/models/
