name: tfm_app
description: "Predictive Irrigation System integration for Farmers."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: ^3.11.5





dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8     # Icons font. Use with the CupertinoIcons class for iOS style icons.
  flutter_blue_plus: ^2.3.1   # BLE interfacing.
  flutter_blue_plus_linux: ^9.0.0 # Explicitly add linux support.
  http: ^1.6.0                # HTTP interface. Useful for Open-meteo API transactions.
  tflite_flutter: ^0.12.1     # Tensorflow for mobile and native flutter execution.
  realm: ^20.2.0              # Database managing.
  flutter_riverpod: ^2.6.1    # State manager.


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0





# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/models/
