import 'dart:math';
import '../core/db/database_service.dart';

class SampleDataSeeder {
  static void seed(DatabaseService db) {
    db.clearDatabase();
    
    final now = DateTime.now();
    final random = Random();

    // 1. Seed 48h of Soil Humidity History (-48h to 0)
    for (int i = 48; i >= 0; i--) {
      final timestamp = now.subtract(Duration(hours: i)).millisecondsSinceEpoch;
      // Sinusoidal humidity with some noise (40-60% range)
      final val = 50.0 + 10.0 * sin(i * 0.2) + (random.nextDouble() * 2.0);
      db.saveSoilHumidity(timestamp, val);
      
      // 2. Seed Weather context (Radiation peaks during day)
      final hour = now.subtract(Duration(hours: i)).hour;
      double radiation = 0;
      if (hour > 7 && hour < 20) {
        radiation = 800 * sin((hour - 7) * pi / 13) + (random.nextDouble() * 50);
      }
      db.saveWeather(timestamp, 25.0, 50.0, max(0, radiation), 0.0);
    }

    // 3. Seed 24h of Future Predictions (0 to +24h)
    // Note: In real app, these are generated by LSTM.
    for (int i = 1; i <= 24; i++) {
      final timestamp = now.add(Duration(hours: i)).millisecondsSinceEpoch;
      // Predicted drop if no irrigation
      final val = 50.0 - (i * 0.8) + (random.nextDouble() * 1.0);
      db.savePrediction(timestamp, val, "LSTM PROJECTION (NO IRRIGATION)");
    }
  }
}
