// ponytail: Simple localization dictionary to easily translate app texts
import 'package:flutter_riverpod/flutter_riverpod.dart';

final localeProvider = StateProvider<String>((ref) => 'en'); // 'en' or 'es'

const Map<String, Map<String, String>> translations = {
  'en': {
    'app_title_telem': 'IoT Station Telemetry',
    'app_title_gps': 'Geospatial Settings',
    'app_title_conf': 'System Configuration',
    'ble_console': 'BLE Debug Console',
    'status_connected': 'Status: Connected (Authenticated)',
    'status_disconnected': 'Status: Disconnected',
    'sync_time': 'Sync Time',
    'send_weather': 'Send Weather',
    'get_raw': 'Get Raw History',
    'get_pred': 'Get Pred History',
    'trigger_lstm': 'Trigger LSTM',
    'toggle_debug': 'Toggle Station Debug',
    'saturation_risk': 'SATURATION RISK',
    'healthy_safe': 'HEALTHY (SAFE)',
    'weather_bridge': 'Weather Data Bridge',
    'avg_temp': 'Avg Temp',
    'avg_hum': 'Avg Hum',
    'send_env_data': 'Send Env Data (0x02)',
    'inference_layer': 'Inference Layer (Phase 4)',
    'status': 'Status',
    'last_run': 'Last Run',
    'rf_loaded': 'RF Model Loaded',
    'recommendation': 'Recommendation',
    'run_rf': 'Run RF Inference (Fusion)',
    'location_controls': 'Location Controls',
    'active_saved': 'Active Saved Coords',
    'pending_marker': 'Pending Marker Coords',
    'gps_accuracy': 'GPS Accuracy',
    'gps_error': 'GPS Polling failed',
    'setup_context': 'Setup Device Config Context',
    'db_maintenance': 'Database Maintenance',
    'purge_db': 'Purge Local Database',
    'purge_warning': 'Warning: All historical records, weather information, and predictions will be permanently deleted.',
    'clear_db': 'Clear Database',
    'threshold_params': 'Threshold Parameters',
    'humidity_alert': 'Station Humidity Alert Target (%)',
    'weather_freq': 'API Weather Update Frequency (Hours)',
    'disconnect_station': 'Disconnect Station',
    'active_node': 'Active Node',
    'scan_stations': 'Scan for Stations',
    'discovered_stations': 'Discovered Stations',
    'all_stations': 'All Stations Inventory',
    'language_settings': 'Language Settings',
    'sync_stage_idle': 'Idle',
    'sync_stage_connecting': 'Connecting',
    'sync_stage_pairing': 'Pairing',
    'sync_stage_refreshing': 'Synchronizing',
    'sync_stage_completed': 'Success',
    'sync_stage_failed': 'Failed',
    'sync_step_connect': 'Device Connection',
    'sync_step_pair': 'Security Handshake',
    'sync_step_refresh': 'Data Synchronization',
    'sync_close': 'Close',
    'sync_cancel': 'Cancel',
  },
  'es': {
    'app_title_telem': 'Telemetría de la Estación',
    'app_title_gps': 'Configuración Geosespacial',
    'app_title_conf': 'Configuración del Sistema',
    'ble_console': 'Consola de Depuración BLE',
    'status_connected': 'Estado: Conectado (Autenticado)',
    'status_disconnected': 'Estado: Desconectado',
    'sync_time': 'Sincronizar Hora',
    'send_weather': 'Enviar Clima',
    'get_raw': 'Obtener Historial',
    'get_pred': 'Obtener Predicciones',
    'trigger_lstm': 'Disparar LSTM',
    'toggle_debug': 'Depuración de Estación',
    'saturation_risk': 'RIESGO DE SATURACIÓN',
    'healthy_safe': 'SANO (SEGURO)',
    'weather_bridge': 'Puente de Datos Climáticos',
    'avg_temp': 'Temp Promedio',
    'avg_hum': 'Hum Promedio',
    'send_env_data': 'Enviar Datos Climáticos (0x02)',
    'inference_layer': 'Capa de Inferencia (Fase 4)',
    'status': 'Estado',
    'last_run': 'Última Ejecución',
    'rf_loaded': 'Modelo RF Cargado',
    'recommendation': 'Recomendación',
    'run_rf': 'Ejecutar Inferencia RF',
    'location_controls': 'Controles de Ubicación',
    'active_saved': 'Coordenadas Guardadas',
    'pending_marker': 'Coordenadas Pendientes',
    'gps_accuracy': 'Precisión GPS',
    'setup_context': 'Contexto de Configuración',
    'db_maintenance': 'Mantenimiento de BD',
    'purge_db': 'Purgar Base de Datos',
    'purge_warning': 'Advertencia: Todos los registros históricos, datos climáticos y predicciones se eliminarán permanentemente.',
    'clear_db': 'Limpiar Base de Datos',
    'threshold_params': 'Parámetros de Umbral',
    'humidity_alert': 'Objetivo de Alerta de Humedad (%)',
    'weather_freq': 'Frecuencia de Clima API (Horas)',
    'disconnect_station': 'Desconectar Estación',
    'active_node': 'Nodo Activo',
    'scan_stations': 'Buscar Estaciones',
    'discovered_stations': 'Estaciones Descubiertas',
    'all_stations': 'Inventario de Estaciones',
    'language_settings': 'Ajustes de Idioma',
    'sync_stage_idle': 'Inactivo',
    'sync_stage_connecting': 'Conectando',
    'sync_stage_pairing': 'Emparejando',
    'sync_stage_refreshing': 'Sincronizando',
    'sync_stage_completed': 'Completado',
    'sync_stage_failed': 'Fallido',
    'sync_step_connect': 'Conexión del Dispositivo',
    'sync_step_pair': 'Emparejamiento de Seguridad',
    'sync_step_refresh': 'Sincronización de Datos',
    'sync_close': 'Cerrar',
    'sync_cancel': 'Cancelar',
  }
};

extension LocalizedStrings on WidgetRef {
  String tr(String key) {
    final locale = watch(localeProvider);
    return translations[locale]?[key] ?? translations['en']?[key] ?? key;
  }
}
